spring.jpa:
  hibernate.ddl-auto: create-drop
  show-sql: false

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${databaseLink}
  username: ${dbUsername}
  password: ${dbPassword}